const ACTIONS = {
  POKEMON: {
    BEGIN_FETCH: 'BEGIN_POKEMON_LIST_FETCH',
    SET: 'SET_POKEMON_DATA',
    START_LOADING: 'POKEMON_DATA_START_LOADING',
    STOP_LOADING: 'POKEMON_DATA_STOP_LOADING',
  },
  LOADING: {
    START: 'START',
    STOP: 'STOP',
  }
}

export default ACTIONS;
